language: python

python:
    - 2.7

env:
    - TWISTED=Twisted==12.2
    - TWISTED=Twisted==12.3
    - TWISTED=svn+svn://svn.twistedmatrix.com/svn/Twisted/trunk

install:
    - pip install pyflakes --use-mirrors
    - pip install -q $TWISTED --use-mirrors
    - python setup.py install

script:
    - pyflakes twittytwister
    - trial twittytwister
